name: Get Kworb Daily Charts and Tweet

on:
  schedule:
    - cron: '0 0 * * *' # 毎日午前0時 (UTC) に実行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # CSVファイルをコミットするため
      # tweets: write # GitHubトークン経由でのTwitterへの直接的な権限付与は不可。Pythonスクリプト内の認証を使用。

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # `tweepy` を追加でインストール
        pip install requests beautifulsoup4 pandas tweepy

    - name: Ensure charts directory exists
      run: |
        mkdir -p charts

    - name: Run Kworb Chart Scraper
      id: run_scraper # ステップにIDを追加
      run: |
        python kworb.py
      # ここで生成されたCSVは `Commit and push charts` でプッシュされる

    - name: Extract Top 5 and Tweet
      env: # 環境変数を設定
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: |
        python top5.py # 修正したPythonスクリプトを実行

    - name: Commit and push charts
      run: |
        git config user.name "${{ secrets.GH_USER_NAME }}"
        git config user.email "${{ secrets.GH_USER_EMAIL }}"
        
        git add charts/*.csv
        
        if git diff --staged --quiet; then
          echo "No changes to commit. Exiting."
        else
          git commit -m "Add daily Kworb charts for ${{ github.run_number }}"
          git push
        fi
