name: Get Kworb Daily Charts

on:
  schedule:
    # 9:05AM JST 
    - cron: '5 0 * * *'
  workflow_dispatch:
    # GitHub UIから手動でワークフローを実行できるようにする

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas

    - name: Ensure charts directory exists
      run: |
        mkdir -p charts

    - name: Run Kworb Chart Scraper
      run: |
        python kworb.py

    - name: Commit and push charts
      run: |
        git config user.name "${{ secrets.GH_USER_NAME }}"
        git config user.email "${{ secrets.GH_USER_EMAIL }}"
        git add charts/*.csv
        git diff-index --quiet HEAD || git commit -m "Add daily Kworb charts for ${{ github.run_number }}"
        git push
