name: Tweet Daily Top 5 Charts

on:
  schedule:
    - cron: '10 3 * * *' 
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # ツイートのみなので contents: write は不要 (デフォルトでread権限はある)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies for Tweeting
      run: |
        python -m pip install --upgrade pip
        pip install pandas tweepy

    - name: Extract Top 5 and Tweet
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: |
        python top5.py
